#!/bin/bash
####################################################################################
###
### GRAM miner for ton.ninja
### os.dog integration: shatll(@osdog)
###
####################################################################################

#	example
#
#	{
#		"miner":"lolminer",
#		"algo":"nexapow",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"1.82a",
#		"temp":[31,28,29,29,31,29,30,30],
#		"temp2":[38,35,35,35,37,34,37,37],
#		"temp3":[0,0,0,0,0,0,0,0],
#		"fan":[45,45,44,45,44,44,45,46],
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["03","05","06","07","09","0b","0c","0d"],
#		"coin":"NEXA"
#	}

#echo '{"algo":"sha256","coin":"mrdn","busid":["03","05","06","07","09","0b","0c","0d"]}'

busid=`cat /run/dog/gpuStats | jq '[.gpu[].b]'`
algo="SHA256"
miner="miningPoolCli"

data=$(
		jq -n \
		--argjson busid "$busid" \
		--arg algo "$algo" \
		--arg miner "$miner" \
		'{
			$miner,
			$algo,
			$busid
		}'
)

echo "$data" | jq -c
